!classDefinition: #I category: #Ejercicio4!
DenotativeObject subclass: #I
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Ejercicio4'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'I class' category: #Ejercicio4!
I class
	instanceVariableNames: ''!

!I class methodsFor: 'Operaciones' stamp: 'OK 3/21/2024 11:37:29'!
* aMultiplicand! !

!I class methodsFor: 'Operaciones' stamp: 'OK 3/21/2024 11:36:57'!
+ anAdder! !

!I class methodsFor: 'Operaciones' stamp: 'OK 3/21/2024 11:37:17'!
- sustrahend! !

!I class methodsFor: 'Operaciones' stamp: 'OK 3/21/2024 11:37:36'!
/ dividend! !

!I class methodsFor: 'Operaciones' stamp: 'OK 3/21/2024 11:35:42'!
next! !

!I class methodsFor: 'Operaciones' stamp: 'OK 3/21/2024 11:35:34'!
previous! !


!classDefinition: #II category: #Ejercicio4!
DenotativeObject subclass: #II
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Ejercicio4'!
